### ISSUE TITLE
Fragment-文件夹选择文件-点击崩溃

### ISSUE THREAD

**Issue by ForFrog** [imLibo/FilePicker#10]
RT;
Caused by: org.greenrobot.eventbus.**EventBusException**: Subscriber class com.ess.filepicker.activity.SelectFileByBrowserActivity and its super classes have no public methods with the @Subscribe annotation
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:67)
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:140)
        at **com.ess.filepicker.activity.SelectFileByBrowserActivity.onCreate(SelectFileByBrowserActivity.java:81)**
        at android.app.Activity.performCreate(Activity.java:7372)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)

**Comment by ForFrog** [comment]
取消在SelectFileByBrowserActivity中注册eventBus可以解决该问题;
